- db/migrate/20230918084028_create_order_details.rb
> マイグレートファイルadmin,order_detail

- app/assets/stylesheets/public/addresses.scss
- app/assets/stylesheets/public/cart_items.scss
- app/assets/stylesheets/public/customers.scss
- app/assets/stylesheets/public/homes.scss
- app/assets/stylesheets/public/items.scss
- app/assets/stylesheets/public/orders.scss
- app/controllers/public/addresses_controller.rb
- app/controllers/public/cart_items_controller.rb
- app/controllers/public/customers_controller.rb
- app/controllers/public/homes_controller.rb
- app/controllers/public/items_controller.rb
- app/controllers/public/orders_controller.rb
- app/helpers/public/addresses_helper.rb
- app/helpers/public/cart_items_helper.rb
- app/helpers/public/customers_helper.rb
- app/helpers/public/homes_helper.rb
- app/helpers/public/items_helper.rb
- app/helpers/public/orders_helper.rb
- test/controllers/public/addresses_controller_test.rb
- test/controllers/public/cart_items_controller_test.rb
- test/controllers/public/customers_controller_test.rb
- test/controllers/public/homes_controller_test.rb
- test/controllers/public/items_controller_test.rb
- test/controllers/public/orders_controller_test.rb
> Add controller

- app/models/customer.rb
> アソシエーション記載

- db/migrate/20230918075518_devise_create_customers.rb
- db/schema.rb
> マイグレーション済み

- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
> ヘッダーリンクとフッター作成

- app/controllers/admin/items_controller.rb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
> [Add]管理者商品新規登録画面

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/homes_controller.rb
- app/controllers/admin/items_controller.rb
- app/controllers/admin/order_details_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/sessions_controller.rb
- app/views/admin/genres/_new.html.erb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/layouts/_header.html.erb
- db/seeds.rb
ジャンル一覧追加編集
ヘッダーのadminのパス変更
管理者のログインアカウント作成
> ジャンル追加、ヘッダー変更、管理者ログイン登録

- app/controllers/admin/items_controller.rb
- app/models/item.rb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
管理者商品一覧/商品詳細ページを作成
ステータス、商品名のリンクは後程実装予定
> 管理者商品一覧ページの作成

- app/controllers/admin/items_controller.rb
- app/views/admin/items/index.html.erb
- app/views/admin/items/show.html.erb
- config/routes.rb
商品一覧/詳細のステータスの記述を追加
商品一覧の商品名にリンクを追加
商品一覧にページネーションを追加
> 管理者商品一覧/詳細画面の修正

- app/controllers/admin/items_controller.rb
- app/models/item.rb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/items/show.html.erb
> 管理者商品登録時のエラーの修正

- app/views/admin/items/index.html.erb
- app/views/admin/items/show.html.erb
- app/views/public/items/index.html.erb
> 管理者商品詳細画面/一覧画面の修正

- app/controllers/admin/customers_controller.rb
- app/models/customer.rb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/admin/items/edit.html.erb
- app/views/public/items/index.html.erb
> 顧客商品一覧画面の修正

- app/controllers/public/items_controller.rb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
> Add 商品詳細ページ

- app/controllers/public/items_controller.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/show.html.erb
> カートに入れるボタン追加

- app/views/public/addresses/index.html.erb
> 一旦修正したいのでpush

- app/controllers/admin/items_controller.rb
- app/controllers/public/addresses_controller.rb
- app/views/public/addresses/_form.html.erb
- app/views/public/addresses/edit.html.erb
- app/views/public/addresses/index.html.erb
> 配送先システム大体完成

- Gemfile
- Gemfile.lock
- app/controllers/public/orders_controller.rb
- app/models/address.rb
- app/models/order.rb
- app/views/public/orders/comfirm.html.erb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/new.html.erb
- config/application.rb
- config/locales/devise.ja.yml
- config/locales/ja.yml
> order、enum導入、日本語設定

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/orders_controller.rb
- app/models/order.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/orders/show.html.erb
> 顧客編集画面/注文詳細画面の作成

- app/controllers/public/orders_controller.rb
- app/views/public/orders/comfirm.html.erb
- app/views/public/orders/new.html.erb
- db/schema.rb
選択ボタンを追加しましたが自信なしです。最新にしたいためプッシュしました＾＾
> orderラジオフィールド追加

- app/controllers/public/cart_items_controller.rb
- app/views/public/items/index.html.erb
> いろいろ書き換えたり訂正したりしました

- app/controllers/public/orders_controller.rb
- app/views/public/orders/new.html.erb
> order_controller追記

- app/views/public/orders/show.html.erb
> 管理者と顧客の注文履歴詳細

- app/controllers/public/cart_items_controller.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
> いろんなとこ触ってます

- app/controllers/admin/order_details_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order_detail.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- config/locales/ja.yml
コントローラー変更
confirm, new, 動作問題なし
show, index待ち、complete完了
注文ステータス、製作ステータスの日本語設定追加しました。
> confirm address errorあり

- app/controllers/admin/order_details_controller.rb
- config/locales/ja.yml
> order_detail製作ステータス

- app/controllers/public/cart_items_controller.rb
- app/views/layouts/_header.html.erb
- config/routes.rb
> カートアイテム機能多分完成

- app/views/public/registrations/new.html.erb
- app/views/public/sessions/new.html.erb
> ログイン、新規登録形

- app/controllers/admin/orders_controller.rb
>  注文ステータスの更新

- app/controllers/public/orders_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/models/order.rb
- app/views/admin/genres/_new.html.erb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/sessions/new.html.erb
> レイアウト細かい修正

- app/controllers/public/orders_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/models/order.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/admin/homes/top.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
> 注文コントローラー編集、管理者レイアウト

- app/controllers/public/orders_controller.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/show.html.erb
- config/routes.rb
> 注文履歴詳細画面の修正

- app/views/admin/orders/show.html.erb
>  注文履歴詳細画面の修正

- app/controllers/admin/orders_controller.rb
- app/controllers/admin/sessions_controller.rb
- app/views/layouts/_header.html.erb
- config/routes.rb
> topページ関連修正

- app/controllers/public/homes_controller.rb
- app/controllers/public/items_controller.rb
- app/javascript/stylesheets/application.scss
- app/views/public/homes/top.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- app/views/public/sessions/new.html.erb
- config/initializers/kaminari_config.rb
- config/locales/kaminari_design.yml
> いろいろレイアウトさわったやーつ

- app/javascript/stylesheets/application.scss
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/locales/kaminari_design.yml
> ページネーション色変更

- app/controllers/admin/orders_controller.rb
- app/views/admin/customers/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
- app/views/admin/orders/index.html.erb
- app/views/public/genres/_genre.html.erb
> ページネーション増やした

- app/views/admin/orders/index.html.erb
- app/views/admin/orders/show.html.erb
- app/views/public/genres/_genre.html.erb
- app/views/public/orders/show.html.erb
> admin customer注文ステータス追加

- app/controllers/public/sessions_controller.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/customers/show.html.erb
カート内アイテムのレイアウトとかマイページのレイアウトとかあとログイン後の遷移とかとかとか
> いろいろ書き換えました

- app/views/admin/items/edit.html.erb
> admin edit btn変更
